import os
from datetime import datetime


def generate_report(target, analysis, findings):
    """
    Internal draft report generator.
    Output is meant for analyst review, not direct client delivery.
    """

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    safe_target = target.replace("/", "_")

    target_dir = f"reports/scans/{safe_target}"
    os.makedirs(target_dir, exist_ok=True)

    filename = f"scan_{timestamp.replace(':', '-')}.md"
    filepath = os.path.join(target_dir, filename)

    report = f"""# 🔐 AutoSec AI – Security Report (Internal Draft)

## Target
{target}

## Scan Time
{timestamp}

## Overall Risk
🟡 {analysis.get("risk_level", "Unknown") if analysis else "Unknown"}

---

## 🧭 Security Context

This assessment represents a **baseline external security checkup** focused on
publicly exposed services and configurations.

This scan does **not** include:
- Authentication testing
- Authorization bypass
- Business logic analysis
- Exploitation of vulnerabilities

---

## 🔍 Technical Findings
"""

    if not findings:
        report += "\n- No significant findings detected.\n"
    else:
        for f in findings:
            report += (
                f"\n### {f.get('title', 'Finding')}\n"
                f"- Severity: **{f.get('severity', 'info')}**\n"
                f"- Description: {f.get('description', '')}\n"
            )

            evidence = f.get("evidence")
            if evidence:
                report += f"- Evidence: `{evidence}`\n"

            recommendation = f.get("recommendation")
            if recommendation:
                report += f"- Recommendation: {recommendation}\n"

    if analysis:
        report += f"""
---

## 🧠 AI Risk Summary
{analysis.get("summary", "No summary provided.")}

---

## 🛠️ Analyst Notes / Next Actions
{analysis.get("recommendation", "Review findings manually.")}
"""

    report += """

---

Generated by **AutoSec AI**
"""

    with open(filepath, "w") as f:
        f.write(report)

    return filepath
