import os
from datetime import datetime

def generate_report(target, analysis, scan_results, nikto_results=None):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    safe_target = target.replace("/", "_")

    target_dir = f"reports/scans/{safe_target}"
    os.makedirs(target_dir, exist_ok=True)

    filename = f"scan_{timestamp.replace(':', '-')}.md"
    filepath = os.path.join(target_dir, filename)

    report = f"""# 🔐 AutoSec AI – Security Report

## Target
{target}

## Scan Time
{timestamp}

## Overall Risk
🟡 {analysis.get("risk_level", "Unknown")}

---

## 🧭 Security Context

This assessment represents a **baseline security checkup** focused on publicly exposed
services, network configuration, and common web misconfigurations.

No critical infrastructure-level vulnerabilities were identified during this scan.
However, this assessment does **not** include deep application-layer testing,
authentication testing, or business logic analysis.

---

## 🔍 Technical Findings
"""

    # Technical findings
    for r in scan_results:
        if r.get("state") == "open":
            report += (
                f"- **Port {r['port']}** ({r['service']} {r['version']})\n"
                f"  Severity: **{r.get('severity', 'Unknown')}**\n"
            )

            # CVE details (limited to avoid noise)
            for cve in r.get("cves", [])[:2]:
                report += (
                    f"  - CVE: {cve.get('id')} – "
                    f"{cve.get('description', '')[:120]}...\n"
                )

            report += "\n"

    # Nikto section (if applicable)
    if nikto_results:
        report += """---
## 🌐 Web Vulnerability Scan (Nikto)
"""
        vulns = nikto_results.get("vulnerabilities", [])
        if vulns:
            for v in vulns[:5]:
                report += f"- {v.get('msg', 'Potential web vulnerability detected')}\n"
        else:
            report += "- No major web vulnerabilities detected during web scan.\n"

    report += f"""
---

## 🧠 AI Risk Summary
{analysis.get("summary", "No summary provided.")}

---

## 🛠️ Recommended Actions
{analysis.get("recommendation", "No recommendations provided.")}

---

Generated by **AutoSec AI**
"""

    with open(filepath, "w") as f:
        f.write(report)

    return filepath
